#GitHub action to build and deploy spring boot project runing on java 17 on EC2 instace running AWS linux using SSH
name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
deploy:
runs-on: aws linux 2
steps:
- name: Checkout code
uses: actions/checkout@v2
- name: Set up JDK 17 
uses: actions/setup-java@v2
with:
  java-version: '17'
  distribution: 'temurin'
- name: Build with Maven
run: mvn clean package -DskipTests
- name: SSH into EC2 instance
uses: appleboy/scp-action@master
with:
host: ${{ secrets.HOST }}
username: ${{ secrets.USERNAME }}
key: ${{ secrets.SSH_KEY }}
source: "target/*.jar"
destination: "/home/${{ secrets.USERNAME }}/app.jar"
- name: Run the application
run: |
ssh -o "StrictHostKeyChecking=no" ${secrets.USERNAME}@${secrets.HOST} << 'EOF'
sudo java -jar /home/${secrets.USERNAME}/app.jar
EOF





